### ISSUE TITLE
Structurempa.WebAPI2 requires System.Web.Mvc

### ISSUE THREAD

**Issue by blaiseliu** [webadvanced/Structuremap.WebAPI2#2]
Some of my projects are WebAPI only. There is no **Microsoft.AspNet.Mvc** installed. 

When installing **Structuremap.WebAPI2**, the created class **StructuremapMvc** has a reference to **System.Web.Mvc**.

Is it possible to implement the DI without **System.Web.Mvc**?

**Comment by valmont** [comment]
Yes. But you would have to update the files added to your project. You can read more here: http://www.webadvanced.com/blog/asp.net-mvc-4-web-api-and-structuremap

**Comment by mauriciod73** [comment]
Yes, but this really doesn't solve anything, the problem I see is that when we have pure webapi projects that need DI and we install the StructureMap WebApi2 nuget, it drags dependencies to MVC, and that only contributes to obscuring the code. A workaround would be to only install the core of structuremap and have each dev implement the dependency resolver for webapi, but then, why have a nuget that in theory already does it

**Comment by justinmichaels** [comment]
I agree with the other comments.  Breaking out the WebAPI specific DI in to it's own NuGet package without a dependency on MVC would be preferred.  The url you referenced above gives me a 404 error.
